Prevent debug package build to workaround build issue on Alma9
Would get:

 + /usr/lib/rpm/redhat/brp-mangle-shebangs
 Processing files: libempserver-1.1.0-2.xcpng8.99.x86_64
 Provides: libempserver = 1.1.0-2.xcpng8.99 libempserver(x86-64) = 1.1.0-2.xcpng8.99 libempserver.so.1()(64bit)
 Requires(interp): /sbin/ldconfig /sbin/ldconfig
 Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
 Requires(post): /sbin/ldconfig /sbin/ldconfig
 Requires(postun): /sbin/ldconfig /sbin/ldconfig
 Requires: libc.so.6()(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.34)(64bit) rtld(GNU_HASH)
 Processing files: libempserver-debugsource-1.1.0-2.xcpng8.99.x86_64
 error: Empty %files file /data/src/xcpng/rpms/libempserver/BUILD/libempserver-1.1.0/debugsourcefiles.list

 RPM build errors:
     Empty %files file /data/src/xcpng/rpms/libempserver/BUILD/libempserver-1.1.0/debugsourcefiles.list